import React, { useState, useRef, useEffect } from 'react';
import './App.css';

function App() {
  const [image, setImage] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [userProfile, setUserProfile] = useState({
    name: '',
    role: 'Quality Control Specialist',
    company: '',
    expertise: []
  });
  const [reports, setReports] = useState([]);
  const fileInputRef = useRef(null);
  const videoRef = useRef(null);
  const canvasRef = useRef(null);

  // Simulated AI analysis function
  const analyzeImage = async (imageData) => {
    setLoading(true);
    
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Mock analysis results
    const mockAnalysis = {
      overallQuality: Math.random() > 0.3 ? 'PASS' : 'FAIL',
      confidence: (Math.random() * 0.3 + 0.7).toFixed(2),
      defects: [
        { type: 'Surface Scratch', severity: 'Minor', location: 'Top-left quadrant' },
        { type: 'Color Variation', severity: 'Moderate', location: 'Center region' }
      ].filter(() => Math.random() > 0.5),
      dimensions: {
        width: (Math.random() * 10 + 90).toFixed(2) + 'mm',
        height: (Math.random() * 10 + 90).toFixed(2) + 'mm',
        tolerance: '±0.1mm'
      },
      recommendations: [
        'Adjust surface finishing process',
        'Review color consistency parameters',
        'Implement additional quality checkpoints'
      ],
      timestamp: new Date().toISOString()
    };
    
    setAnalysis(mockAnalysis);
    setLoading(false);
    
    // Add to reports for professional portfolio
    const newReport = {
      id: Date.now(),
      image: imageData,
      analysis: mockAnalysis,
      inspector: userProfile.name || 'Anonymous',
      date: new Date().toLocaleDateString()
    };
    
    setReports(prev => [newReport, ...prev.slice(0, 9)]); // Keep last 10 reports
  };

  const handleImageUpload = (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const imageData = e.target.result;
        setImage(imageData);
        analyzeImage(imageData);
      };
      reader.readAsDataURL(file);
    }
  };

  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true });
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
    } catch (err) {
      console.error('Error accessing camera:', err);
    }
  };

  const captureImage = () => {
    if (videoRef.current && canvasRef.current) {
      const canvas = canvasRef.current;
      const video = videoRef.current;
      const context = canvas.getContext('2d');
      
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      context.drawImage(video, 0, 0);
      
      const imageData = canvas.toDataURL('image/jpeg');
      setImage(imageData);
      analyzeImage(imageData);
      
      // Stop camera
      const stream = video.srcObject;
      const tracks = stream.getTracks();
      tracks.forEach(track => track.stop());
    }
  };

  const generateProfessionalReport = () => {
    if (!analysis) return;
    
    const report = `
# Quality Control Report
**Inspector:** ${userProfile.name || 'Anonymous'}
**Date:** ${new Date().toLocaleDateString()}
**Company:** ${userProfile.company || 'N/A'}

## Analysis Summary
- **Overall Quality:** ${analysis.overallQuality}
- **Confidence Level:** ${(analysis.confidence * 100).toFixed(1)}%
- **Inspection Method:** AI-Powered Visual Analysis

## Defects Identified
${analysis.defects.length > 0 ? 
  analysis.defects.map(defect => 
    `- **${defect.type}** (${defect.severity}): ${defect.location}`
  ).join('\n') : 
  '- No defects detected'
}

## Dimensional Analysis
- Width: ${analysis.dimensions.width}
- Height: ${analysis.dimensions.height}
- Tolerance: ${analysis.dimensions.tolerance}

## Professional Recommendations
${analysis.recommendations.map(rec => `- ${rec}`).join('\n')}

---
*Generated by QualityBrand AI - Enhancing Manufacturing Excellence*
    `;
    
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `quality-report-${Date.now()}.md`;
    a.click();
  };

  return (
    <div className="App">
      <header className="app-header">
        <h1>🔍 QualityBrand AI</h1>
        <p>AI-Powered Visual Inspection for Manufacturing Excellence</p>
      </header>

      <div className="profile-section">
        <h2>Professional Profile</h2>
        <div className="profile-inputs">
          <input
            type="text"
            placeholder="Your Name"
            value={userProfile.name}
            onChange={(e) => setUserProfile({...userProfile, name: e.target.value})}
          />
          <input
            type="text"
            placeholder="Company"
            value={userProfile.company}
            onChange={(e) => setUserProfile({...userProfile, company: e.target.value})}
          />
        </div>
      </div>

      <div className="inspection-section">
        <h2>Quality Inspection</h2>
        <div className="upload-options">
          <button onClick={() => fileInputRef.current?.click()}>
            📁 Upload Image
          </button>
          <button onClick={startCamera}>
            📷 Use Camera
          </button>
          <input
            type="file"
            ref={fileInputRef}
            onChange={handleImageUpload}
            accept="image/*"
            style={{ display: 'none' }}
          />
        </div>

        <div className="camera-section">
          <video ref={videoRef} autoPlay style={{ maxWidth: '100%', display: 'none' }} />
          <canvas ref={canvasRef} style={{ display: 'none' }} />
          <button onClick={captureImage} style={{ display: videoRef.current?.srcObject ? 'block' : 'none' }}>
            📸 Capture
          </button>
        </div>

        {image && (
          <div className="image-preview">
            <img src={image} alt="Inspection" style={{ maxWidth: '100%', maxHeight: '400px' }} />
          </div>
        )}

        {loading && (
          <div className="loading">
            <div className="spinner"></div>
            <p>Analyzing image with AI...</p>
          </div>
        )}

        {analysis && (
          <div className="analysis-results">
            <h3>Analysis Results</h3>
            <div className={`quality-status ${analysis.overallQuality.toLowerCase()}`}>
              <strong>Quality Status: {analysis.overallQuality}</strong>
              <span className="confidence">Confidence: {(analysis.confidence * 100).toFixed(1)}%</span>
            </div>

            {analysis.defects.length > 0 && (
              <div className="defects">
                <h4>Defects Detected:</h4>
                {analysis.defects.map((defect, index) => (
                  <div key={index} className="defect-item">
                    <strong>{defect.type}</strong> ({defect.severity}) - {defect.location}
                  </div>
                ))}
              </div>
            )}

            <div className="dimensions">
              <h4>Dimensional Analysis:</h4>
              <p>Width: {analysis.dimensions.width} | Height: {analysis.dimensions.height}</p>
              <p>Tolerance: {analysis.dimensions.tolerance}</p>
            </div>

            <div className="recommendations">
              <h4>Professional Recommendations:</h4>
              <ul>
                {analysis.recommendations.map((rec, index) => (
                  <li key={index}>{rec}</li>
                ))}
              </ul>
            </div>

            <button className="generate-report" onClick={generateProfessionalReport}>
              📄 Generate Professional Report
            </button>
          </div>
        )}
      </div>

      <div className="portfolio-section">
        <h2>Professional Portfolio</h2>
        <p>Build your expertise with documented quality inspections</p>
        <div className="stats">
          <div className="stat-item">
            <strong>{reports.length}</strong>
            <span>Inspections Completed</span>
          </div>
          <div className="stat-item">
            <strong>{reports.filter(r => r.analysis.overallQuality === 'PASS').length}</strong>
            <span>Passed Items</span>
          </div>
          <div className="stat-item">
            <strong>{reports.reduce((acc, r) => acc + r.analysis.defects.length, 0)}</strong>
            <span>Defects Identified</span>
          </div>
        </div>

        {reports.length > 0 && (
          <div className="recent-reports">
            <h3>Recent Inspections</h3>
            <div className="reports-grid">
              {reports.slice(0, 6).map(report => (
                <div key={report.id} className="report-card">
                  <img src={report.image} alt="Inspection" />
                  <div className="report-info">
                    <div className={`status ${report.analysis.overallQuality.toLowerCase()}`}>
                      {report.analysis.overallQuality}
                    </div>
                    <p>{report.date}</p>
                    <p>{report.analysis.defects.length} defects</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <footer className="app-footer">
        <p>🚀 Enhance your manufacturing career with AI-powered quality control</p>
        <p>Built with ❤️ for manufacturing professionals</p>
      </footer>
    </div>
  );
}

export default App;